trailingComma: es5
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
printWidth: 100
arrowParens: avoid
proseWrap: preserve
overrides:
  - files: '*.yml'
    options:
      parser: yaml
      semi: false
  - files: ['*.tsx', '*.ts']
    options:
      parser: typescript
      arrowParens: avoid